export const RECEIVE_PAGES = 'RECEIVE_PAGES';
export const GET_COUNT_PAGES = 'GET_COUNT_PAGES';
export const SEARCH_ISSUES = 'SEARCH_ISSUES';
export const REQUEST_ISSUES = 'REQUEST_ISSUES';
export const RECEIVE_ISSUES = 'RECEIVE_ISSUES';
export const SHOW_ERROR = 'SHOW_ERROR';
